name: Laravel

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.4'
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Spin up container
        run: docker compose up -d
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Generate key
        run: docker compose exec -T app php artisan key:generate
      - name: Run Migrations
        run: docker compose exec -T app php artisan migrate:fresh --seed --env=testing --force
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        run: docker compose exec -T app vendor/bin/pest
      - name: Spin down container
        if: always()
        run: docker compose down -v
