name: Laravel

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      testDB:
        image: postgres
        env:
          POSTGRES_ROOT_PASSWORD: password
          POSTGRES_DATABASE: atomeq
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        ports:
          - 5434:5432

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.4'
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Copy Testing .env
        run: cp ./.env.testing.example ./.env.testing
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Run Migrations
        run: php artisan migrate --env=testing
      - name: Generate key
        run: php artisan key:generate
      - name: Copy Periodic Table CSV
        run: cp ./storage/Periodic_Table_of_Elements.csv ./storage/app/private
      - name: Execute tests (Unit and Feature tests) via Pest
        run: php artisan test
      - name: Spin down container
        if: always()
        run: docker compose down -v
